### ISSUE TITLE
assert len(data.shape) == 3 and data.shape[-1] == 3  AssertionError

### ISSUE THREAD

**Issue by RuiqingTang** [L-Sun/LGTM#8]
When I run `bash prepare_data_models.sh`, I get the error.
`Get h3d features from Guo et al.
The processed motions will be stored in this folder:
datasets/motions/guoh3dfeats
  0%|                                                                                                                                                         | 0/15136 [00:00<?, ?it/s]Error executing job with overrides: []
Traceback (most recent call last):
  File "/data/newhome/weizixiong/Projects/LGTM/third_packages/TMR/prepare/compute_guoh3dfeats.py", line 79, in compute_guoh3dfeats
    joints_m = swap_left_right(joints)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/newhome/weizixiong/Projects/LGTM/third_packages/TMR/prepare/compute_guoh3dfeats.py", line 21, in swap_left_right
    assert len(data.shape) == 3 and data.shape[-1] == 3
                                    ^^^^^^^^^^^^^^^^^^^
AssertionError

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
 30%|█████████████████████████████████████████▋                                                                                                 | 4534/15136 [00:00<00:00, 49106.10it/s]`

**Comment by Zhong1025** [comment]
Have you solved this problem now?i run it,too.And i found this.(lgtm) (base) root@autodl-container-7f754eadf3-116f25fc:~/autodl-tmp/LGTM-main/third_packages/TMR/prepare# python -m prepare.compute_guoh3dfeats
python -m prepare.compute_body_part_guoh3dfeats part_name=head
python -m prepare.compute_body_part_guoh3dfeats part_name=left_arm
python -m prepare.compute_body_part_guoh3dfeats part_name=right_arm
python -m prepare.compute_body_part_guoh3dfeats part_name=torso
python -m prepare.compute_body_part_guoh3dfeats part_name=left_leg
python -m prepare.compute_body_part_guoh3dfeats part_name=right_leg
Get h3d features from Guo et al.
The processed motions will be stored in this folder:
datasets/motions/guoh3dfeats
0it [00:00, ?it/s]
/root/autodl-tmp/LGTM-main/.env/bin/python: No module named prepare.compute_body_part_guoh3dfeats
/root/autodl-tmp/LGTM-main/.env/bin/python: No module named prepare.compute_body_part_guoh3dfeats
/root/autodl-tmp/LGTM-main/.env/bin/python: No module named prepare.compute_body_part_guoh3dfeats
/root/autodl-tmp/LGTM-main/.env/bin/python: No module named prepare.compute_body_part_guoh3dfeats
/root/autodl-tmp/LGTM-main/.env/bin/python: No module named prepare.compute_body_part_guoh3dfeats
/root/autodl-tmp/LGTM-main/.env/bin/python: No module named prepare.compute_body_part_guoh3dfeats

**Comment by RuiqingTang** [comment]
@Zhong1025 Sorry, I have forgotten because the time interval is too long.
